
@url = http://localhost:3000
//test@1234,password

#Create New Acccount -> working
# remove balance from here - for testing purpose only
POST  {{url}}/account
content-type: application/json

{
    "first_name": "Vipin",
    "last_name": "Sharma",
    "password":"password",
    "balance":1000
    
}

####################

#Login Into Account -> Under dev
POST {{url}}/login
content-type: application/json

{
    "number" : 594773,
    "password": "password"
}
#################
#Get All Accounts -> working
GET   {{url}}/account

############
#Get Account by ID -> Under Dev
GET {{url}}/account/7
x-jwt-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcnkiOiIyMDI1LTA4LTA3VDE1OjQ2OjU2Ljk1MTEyKzA1OjMwIiwiaWQiOjcsIm51bWJlciI6NTk0NzczfQ.-3JSK_YplMBpjMHAiazRN0jBqD78qi-l0VpsVyMogkU

##########
#Delete account by ID -> Working
DELETE {{url}}/account/delete/4



####################
#Transfer to money to account
POST {{url}}/transfer/7
content-type: application/json
x-jwt-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcnkiOiIyMDI1LTA4LTA3VDE1OjQ2OjU2Ljk1MTEyKzA1OjMwIiwiaWQiOjcsIm51bWJlciI6NTk0NzczfQ.-3JSK_YplMBpjMHAiazRN0jBqD78qi-l0VpsVyMogkU

{
    "to_account": 173374,
    "amount": 550
}