
@url = http://localhost:3000


#Create New Acccount -> working
POST  {{url}}/account
content-type: application/json

{
    "first_name": "Varun",
    "last_name": "Singh",
    "password":"password"
}

####################

#Login Into Account -> Under dev
POST {{url}}/login
content-type: application/json

{
    "number" : 286294,
    "password": "test@1234"
}
#################
#Get All Accounts -> working
GET   {{url}}/account

############
#Get Account by ID -> Under Dev
GET {{url}}/account/2
x-jwt-token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcnkiOiIyMDI1LTA4LTA0VDE2OjE3OjU5LjczMjE2OSswNTozMCIsImlkIjoyLCJudW1iZXIiOjI4NjI5NH0.rmo1GcLSlq2bRgUJYOtPa8kLejSZ-3FL1K1ToPxa7sI

##########
#Delete account by ID -> Working
DELETE {{url}}/account/delete/4



####################
#Transfer to money to account
POST {{url}}/transfer
content-type: application/json

{
    "to_account": 3243254345,
    "amount": 3242345323
}